import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          style={{
            display: "flex",
            gap: "10px",
            padding: "10px",
            backgroundColor: "#f0f0f0",
            color: "#333",
            display: "flex",
            justifyContent: "center",
            marginBottom: "20px",
          }}
        >
          <Link href={"/"}>Home</Link>
          <Link href={"/articles"}>Articles</Link>
          <Link href={"/posts"}>Posts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
